from clingo import Function, Number

DICTS = {
    "ex06.txt": {
        (1, 3): 2,
        (1, 4): 7,
        (1, 5): 4,
        (1, 6): 9,
        (1, 7): 6,
        (1, 8): 8,
        (2, 3): 8,
        (2, 4): 6,
        (2, 5): 3,
        (2, 6): 1,
        (2, 7): 2,
        (2, 8): 7,
        (3, 3): 9,
        (3, 4): 5,
        (3, 5): 2,
        (3, 6): 8,
        (3, 7): 1,
        (3, 8): 3,
        (4, 3): 3,
        (4, 4): 4,
        (4, 5): 8,
        (4, 6): 7,
        (4, 7): 5,
        (4, 8): 6,
        (5, 1): 8,
        (5, 3): 4,
        (5, 4): 2,
        (5, 5): 6,
        (5, 6): 3,
        (5, 7): 7,
        (5, 8): 9,
        (6, 1): 2,
        (6, 2): 7,
        (6, 3): 6,
        (6, 4): 1,
        (6, 5): 9,
        (6, 6): 5,
        (6, 7): 8,
        (6, 8): 4,
        (7, 1): 4,
        (7, 2): 8,
        (7, 3): 5,
        (7, 4): 9,
        (7, 5): 7,
        (7, 6): 2,
        (7, 7): 3,
        (7, 8): 1,
        (8, 1): 6,
        (8, 2): 2,
        (8, 3): 7,
        (8, 4): 3,
        (8, 5): 1,
        (8, 6): 4,
        (8, 7): 9,
        (9, 1): 3,
        (9, 2): 9,
        (9, 3): 1,
        (9, 4): 8,
        (9, 5): 5,
        (9, 6): 6,
        (9, 7): 4,
    },
    "ex15.txt": {
        (1, 4): 7,
        (1, 5): 1,
        (1, 6): 9,
        (1, 7): 5,
        (2, 3): 4,
        (2, 4): 3,
        (2, 5): 6,
        (2, 6): 2,
        (2, 7): 8,
        (3, 3): 9,
        (3, 4): 5,
        (3, 5): 8,
        (3, 6): 4,
        (3, 7): 1,
        (4, 3): 2,
        (4, 4): 1,
        (4, 5): 4,
        (4, 6): 7,
        (4, 7): 9,
        (5, 3): 5,
        (5, 4): 2,
        (5, 5): 9,
        (5, 6): 8,
        (5, 7): 3,
        (6, 3): 1,
        (6, 4): 6,
        (6, 5): 3,
        (6, 6): 5,
        (6, 7): 2,
        (7, 3): 7,
        (7, 4): 4,
        (7, 5): 2,
        (7, 6): 3,
        (8, 3): 3,
        (8, 4): 8,
        (8, 5): 7,
        (8, 6): 6,
        (9, 3): 6,
        (9, 4): 9,
        (9, 5): 5,
        (9, 6): 1,
    },
    "ex12.txt": {
        (1, 4): 7,
        (1, 5): 5,
        (1, 6): 6,
        (1, 7): 8,
        (1, 8): 4,
        (2, 3): 4,
        (2, 4): 9,
        (2, 5): 8,
        (2, 6): 1,
        (2, 7): 2,
        (2, 8): 6,
        (3, 3): 6,
        (3, 4): 2,
        (3, 5): 3,
        (3, 6): 4,
        (3, 7): 5,
        (3, 8): 1,
        (4, 3): 3,
        (4, 4): 6,
        (4, 5): 9,
        (4, 6): 2,
        (4, 7): 4,
        (4, 8): 8,
        (5, 3): 2,
        (5, 4): 5,
        (5, 5): 4,
        (5, 6): 7,
        (5, 7): 3,
        (5, 8): 9,
        (6, 3): 5,
        (6, 4): 8,
        (6, 5): 1,
        (6, 6): 3,
        (6, 7): 7,
        (6, 8): 2,
        (7, 3): 8,
        (7, 4): 1,
        (7, 5): 6,
        (7, 6): 5,
        (7, 7): 9,
        (7, 8): 7,
        (8, 3): 7,
        (8, 4): 4,
        (8, 5): 2,
        (8, 6): 9,
        (8, 7): 6,
        (9, 3): 9,
        (9, 4): 3,
        (9, 5): 7,
        (9, 6): 8,
        (9, 7): 1,
    },
    "ex10.txt": {
        (1, 4): 5,
        (1, 5): 2,
        (1, 6): 8,
        (1, 7): 9,
        (2, 3): 5,
        (2, 4): 7,
        (2, 5): 6,
        (2, 6): 3,
        (2, 7): 4,
        (3, 3): 8,
        (3, 4): 9,
        (3, 5): 4,
        (3, 6): 1,
        (3, 7): 3,
        (4, 3): 4,
        (4, 4): 8,
        (4, 5): 3,
        (4, 6): 5,
        (4, 7): 7,
        (5, 3): 7,
        (5, 4): 2,
        (5, 5): 9,
        (5, 6): 6,
        (5, 7): 1,
        (6, 3): 9,
        (6, 4): 4,
        (6, 5): 1,
        (6, 6): 7,
        (6, 7): 8,
        (7, 3): 3,
        (7, 4): 1,
        (7, 5): 8,
        (7, 6): 2,
        (8, 3): 2,
        (8, 4): 3,
        (8, 5): 7,
        (8, 6): 4,
        (9, 3): 1,
        (9, 4): 6,
        (9, 5): 5,
        (9, 6): 9,
    },
    "ex18.txt": {
        (1, 5): 5,
        (1, 6): 2,
        (1, 7): 6,
        (1, 8): 9,
        (1, 9): 7,
        (2, 5): 6,
        (2, 6): 7,
        (2, 7): 4,
        (2, 8): 8,
        (2, 9): 3,
        (3, 4): 3,
        (3, 5): 4,
        (3, 6): 9,
        (3, 7): 2,
        (3, 8): 5,
        (3, 9): 1,
        (4, 4): 5,
        (4, 5): 3,
        (4, 6): 1,
        (4, 7): 8,
        (4, 8): 7,
        (4, 9): 9,
        (5, 4): 6,
        (5, 5): 2,
        (5, 6): 8,
        (5, 7): 5,
        (5, 8): 1,
        (5, 9): 4,
        (6, 4): 7,
        (6, 5): 9,
        (6, 6): 4,
        (6, 7): 3,
        (6, 8): 2,
        (6, 9): 6,
        (7, 4): 4,
        (7, 5): 7,
        (7, 6): 3,
        (7, 7): 1,
        (7, 8): 6,
        (7, 9): 5,
        (8, 4): 2,
        (8, 5): 1,
        (8, 6): 5,
        (8, 7): 9,
        (8, 8): 4,
        (8, 9): 8,
        (9, 4): 9,
        (9, 5): 8,
        (9, 6): 6,
        (9, 7): 7,
        (9, 8): 3,
    },
    "ex05.txt": {
        (1, 5): 6,
        (1, 6): 2,
        (1, 7): 4,
        (1, 8): 8,
        (1, 9): 9,
        (2, 5): 4,
        (2, 6): 9,
        (2, 7): 1,
        (2, 8): 7,
        (2, 9): 5,
        (3, 4): 1,
        (3, 5): 8,
        (3, 6): 7,
        (3, 7): 6,
        (3, 8): 3,
        (3, 9): 2,
        (4, 4): 6,
        (4, 5): 3,
        (4, 6): 8,
        (4, 7): 9,
        (4, 8): 5,
        (4, 9): 1,
        (5, 4): 9,
        (5, 5): 2,
        (5, 6): 5,
        (5, 7): 8,
        (5, 8): 4,
        (5, 9): 7,
        (6, 4): 4,
        (6, 5): 7,
        (6, 6): 1,
        (6, 7): 3,
        (6, 8): 2,
        (6, 9): 6,
        (7, 4): 8,
        (7, 5): 9,
        (7, 6): 6,
        (7, 7): 7,
        (7, 8): 1,
        (7, 9): 3,
        (8, 4): 7,
        (8, 5): 5,
        (8, 6): 4,
        (8, 7): 2,
        (8, 8): 9,
        (8, 9): 8,
        (9, 4): 2,
        (9, 5): 1,
        (9, 6): 3,
        (9, 7): 5,
        (9, 8): 6,
    },
    "ex02.txt": {
        (1, 3): 6,
        (1, 4): 2,
        (1, 5): 4,
        (1, 6): 8,
        (1, 7): 7,
        (2, 3): 2,
        (2, 4): 3,
        (2, 5): 7,
        (2, 6): 6,
        (2, 7): 8,
        (3, 3): 7,
        (3, 4): 1,
        (3, 5): 9,
        (3, 6): 5,
        (3, 7): 2,
        (4, 3): 4,
        (4, 4): 7,
        (4, 5): 5,
        (4, 6): 3,
        (4, 7): 1,
        (5, 1): 7,
        (5, 3): 8,
        (5, 4): 4,
        (5, 5): 2,
        (5, 6): 9,
        (5, 7): 3,
        (6, 1): 3,
        (6, 2): 9,
        (6, 3): 5,
        (6, 4): 6,
        (6, 5): 8,
        (6, 6): 1,
        (6, 7): 4,
        (7, 1): 2,
        (7, 2): 6,
        (7, 3): 9,
        (7, 4): 8,
        (7, 5): 3,
        (7, 6): 4,
        (8, 1): 4,
        (8, 2): 8,
        (8, 3): 1,
        (8, 4): 5,
        (8, 5): 6,
        (8, 6): 7,
        (9, 1): 5,
        (9, 2): 7,
        (9, 3): 3,
        (9, 4): 9,
        (9, 5): 1,
        (9, 6): 2,
    },
    "ex17.txt": {
        (1, 5): 7,
        (1, 6): 9,
        (1, 7): 3,
        (1, 8): 2,
        (1, 9): 6,
        (2, 5): 3,
        (2, 6): 2,
        (2, 7): 8,
        (2, 8): 4,
        (2, 9): 1,
        (3, 4): 1,
        (3, 5): 8,
        (3, 6): 4,
        (3, 7): 5,
        (3, 8): 9,
        (3, 9): 7,
        (4, 4): 2,
        (4, 5): 4,
        (4, 6): 5,
        (4, 7): 1,
        (4, 8): 8,
        (5, 4): 8,
        (5, 5): 6,
        (5, 6): 1,
        (5, 7): 7,
        (5, 8): 5,
        (6, 4): 7,
        (6, 5): 9,
        (6, 6): 3,
        (6, 7): 4,
        (6, 8): 6,
        (7, 4): 4,
        (7, 5): 1,
        (7, 6): 8,
        (7, 7): 2,
        (7, 8): 3,
        (8, 4): 3,
        (8, 5): 5,
        (8, 6): 6,
        (8, 7): 9,
        (8, 8): 7,
        (9, 4): 9,
        (9, 5): 2,
        (9, 6): 7,
        (9, 7): 6,
        (9, 8): 1,
    },
    "ex16.txt": {
        (1, 4): 7,
        (1, 5): 2,
        (1, 6): 6,
        (1, 7): 4,
        (2, 3): 9,
        (2, 4): 1,
        (2, 5): 8,
        (2, 6): 3,
        (2, 7): 2,
        (3, 3): 6,
        (3, 4): 4,
        (3, 5): 5,
        (3, 6): 9,
        (3, 7): 3,
        (4, 3): 2,
        (4, 4): 9,
        (4, 5): 1,
        (4, 6): 7,
        (4, 7): 8,
        (5, 3): 5,
        (5, 4): 2,
        (5, 5): 3,
        (5, 6): 4,
        (5, 7): 9,
        (6, 3): 7,
        (6, 4): 5,
        (6, 5): 6,
        (6, 6): 8,
        (6, 7): 1,
        (7, 3): 4,
        (7, 4): 3,
        (7, 5): 9,
        (7, 6): 2,
        (8, 3): 1,
        (8, 4): 8,
        (8, 5): 4,
        (8, 6): 5,
        (9, 3): 3,
        (9, 4): 6,
        (9, 5): 7,
        (9, 6): 1,
    },
    "ex08.txt": {
        (1, 3): 4,
        (1, 4): 9,
        (1, 5): 8,
        (1, 6): 6,
        (1, 7): 2,
        (2, 3): 8,
        (2, 4): 2,
        (2, 5): 7,
        (2, 6): 4,
        (2, 7): 1,
        (3, 3): 7,
        (3, 4): 5,
        (3, 5): 1,
        (3, 6): 3,
        (3, 7): 6,
        (4, 3): 6,
        (4, 4): 1,
        (4, 5): 4,
        (4, 6): 8,
        (4, 7): 3,
        (5, 2): 8,
        (5, 3): 1,
        (5, 4): 3,
        (5, 5): 9,
        (5, 6): 2,
        (5, 7): 5,
        (6, 1): 2,
        (6, 2): 4,
        (6, 3): 3,
        (6, 4): 6,
        (6, 5): 5,
        (6, 6): 7,
        (6, 7): 9,
        (7, 1): 8,
        (7, 2): 1,
        (7, 3): 5,
        (7, 4): 7,
        (7, 5): 2,
        (7, 6): 9,
        (8, 1): 4,
        (8, 2): 3,
        (8, 3): 9,
        (8, 4): 8,
        (8, 5): 6,
        (8, 6): 5,
        (9, 1): 6,
        (9, 2): 7,
        (9, 3): 2,
        (9, 4): 4,
        (9, 5): 3,
        (9, 6): 1,
    },
    "ex01.txt": {
        (1, 4): 5,
        (1, 5): 4,
        (1, 6): 9,
        (1, 7): 2,
        (1, 8): 8,
        (1, 9): 3,
        (2, 3): 3,
        (2, 4): 7,
        (2, 5): 1,
        (2, 6): 8,
        (2, 7): 5,
        (2, 8): 6,
        (2, 9): 9,
        (3, 3): 8,
        (3, 4): 2,
        (3, 5): 3,
        (3, 6): 6,
        (3, 7): 1,
        (3, 8): 4,
        (3, 9): 7,
        (4, 3): 1,
        (4, 4): 8,
        (4, 5): 9,
        (4, 6): 5,
        (4, 7): 6,
        (4, 8): 2,
        (4, 9): 4,
        (5, 3): 4,
        (5, 4): 1,
        (5, 5): 6,
        (5, 6): 7,
        (5, 7): 3,
        (5, 8): 9,
        (5, 9): 5,
        (6, 3): 6,
        (6, 4): 3,
        (6, 5): 2,
        (6, 6): 4,
        (6, 7): 8,
        (6, 8): 7,
        (6, 9): 1,
        (7, 3): 5,
        (7, 4): 9,
        (7, 5): 7,
        (7, 6): 2,
        (7, 7): 4,
        (7, 8): 1,
        (7, 9): 8,
        (8, 3): 9,
        (8, 4): 6,
        (8, 5): 5,
        (8, 6): 1,
        (8, 7): 7,
        (8, 8): 3,
        (8, 9): 2,
        (9, 3): 2,
        (9, 4): 4,
        (9, 5): 8,
        (9, 6): 3,
        (9, 7): 9,
        (9, 8): 5,
    },
    "ex04.txt": {
        (1, 4): 3,
        (1, 5): 4,
        (1, 6): 8,
        (1, 7): 5,
        (2, 3): 7,
        (2, 4): 6,
        (2, 5): 1,
        (2, 6): 9,
        (2, 7): 8,
        (3, 3): 6,
        (3, 4): 2,
        (3, 5): 5,
        (3, 6): 7,
        (3, 7): 1,
        (4, 3): 5,
        (4, 4): 4,
        (4, 5): 9,
        (4, 6): 1,
        (4, 7): 6,
        (5, 3): 1,
        (5, 4): 8,
        (5, 5): 6,
        (5, 6): 3,
        (5, 7): 4,
        (6, 3): 8,
        (6, 4): 5,
        (6, 5): 7,
        (6, 6): 2,
        (6, 7): 3,
        (7, 3): 3,
        (7, 4): 1,
        (7, 5): 8,
        (7, 6): 4,
        (8, 3): 2,
        (8, 4): 9,
        (8, 5): 3,
        (8, 6): 5,
        (9, 3): 4,
        (9, 4): 7,
        (9, 5): 2,
        (9, 6): 6,
    },
    "ex14.txt": {
        (1, 4): 1,
        (1, 5): 2,
        (1, 6): 8,
        (1, 7): 4,
        (2, 3): 4,
        (2, 4): 5,
        (2, 5): 6,
        (2, 6): 9,
        (2, 7): 2,
        (3, 3): 6,
        (3, 4): 7,
        (3, 5): 4,
        (3, 6): 3,
        (3, 7): 1,
        (4, 3): 2,
        (4, 4): 4,
        (4, 5): 8,
        (4, 6): 5,
        (4, 7): 6,
        (5, 3): 8,
        (5, 4): 2,
        (5, 5): 3,
        (5, 6): 7,
        (5, 7): 9,
        (6, 3): 7,
        (6, 4): 9,
        (6, 5): 1,
        (6, 6): 6,
        (6, 7): 5,
        (7, 3): 1,
        (7, 4): 6,
        (7, 5): 7,
        (7, 6): 4,
        (8, 3): 5,
        (8, 4): 3,
        (8, 5): 9,
        (8, 6): 1,
        (9, 3): 3,
        (9, 4): 8,
        (9, 5): 5,
        (9, 6): 2,
    },
    "ex09.txt": {
        (1, 3): 9,
        (1, 4): 3,
        (1, 5): 5,
        (1, 6): 4,
        (1, 7): 8,
        (2, 3): 7,
        (2, 4): 2,
        (2, 5): 8,
        (2, 6): 6,
        (2, 7): 4,
        (3, 3): 4,
        (3, 4): 9,
        (3, 5): 7,
        (3, 6): 1,
        (3, 7): 2,
        (4, 3): 5,
        (4, 4): 7,
        (4, 5): 6,
        (4, 6): 8,
        (4, 7): 9,
        (5, 2): 9,
        (5, 3): 6,
        (5, 4): 4,
        (5, 5): 1,
        (5, 6): 3,
        (5, 7): 5,
        (6, 1): 8,
        (6, 2): 7,
        (6, 3): 3,
        (6, 4): 5,
        (6, 5): 2,
        (6, 6): 9,
        (6, 7): 6,
        (7, 1): 9,
        (7, 2): 6,
        (7, 3): 1,
        (7, 4): 8,
        (7, 5): 3,
        (7, 6): 2,
        (8, 1): 7,
        (8, 2): 4,
        (8, 3): 2,
        (8, 4): 1,
        (8, 5): 9,
        (8, 6): 5,
        (9, 1): 5,
        (9, 2): 3,
        (9, 3): 8,
        (9, 4): 6,
        (9, 5): 4,
        (9, 6): 7,
    },
    "ex11.txt": {
        (1, 3): 9,
        (1, 4): 8,
        (1, 5): 6,
        (1, 6): 4,
        (1, 7): 7,
        (2, 3): 3,
        (2, 4): 7,
        (2, 5): 9,
        (2, 6): 1,
        (2, 7): 4,
        (3, 3): 4,
        (3, 4): 3,
        (3, 5): 5,
        (3, 6): 2,
        (3, 7): 8,
        (4, 3): 2,
        (4, 4): 1,
        (4, 5): 4,
        (4, 6): 7,
        (4, 7): 6,
        (5, 1): 7,
        (5, 3): 6,
        (5, 4): 9,
        (5, 5): 8,
        (5, 6): 5,
        (5, 7): 1,
        (6, 1): 5,
        (6, 2): 1,
        (6, 3): 8,
        (6, 4): 6,
        (6, 5): 2,
        (6, 6): 3,
        (6, 7): 9,
        (7, 1): 2,
        (7, 2): 6,
        (7, 3): 5,
        (7, 4): 4,
        (7, 5): 1,
        (7, 6): 8,
        (8, 1): 9,
        (8, 2): 8,
        (8, 3): 7,
        (8, 4): 2,
        (8, 5): 3,
        (8, 6): 6,
        (9, 1): 4,
        (9, 2): 3,
        (9, 3): 1,
        (9, 4): 5,
        (9, 5): 7,
        (9, 6): 9,
    },
    "ex03.txt": {
        (1, 5): 9,
        (1, 6): 4,
        (1, 7): 3,
        (1, 8): 5,
        (1, 9): 7,
        (2, 5): 2,
        (2, 6): 6,
        (2, 7): 9,
        (2, 8): 1,
        (2, 9): 4,
        (3, 4): 3,
        (3, 5): 5,
        (3, 6): 1,
        (3, 7): 8,
        (3, 8): 2,
        (3, 9): 6,
        (4, 4): 4,
        (4, 5): 3,
        (4, 6): 2,
        (4, 7): 1,
        (4, 8): 6,
        (4, 9): 8,
        (5, 4): 6,
        (5, 5): 7,
        (5, 6): 9,
        (5, 7): 2,
        (5, 8): 4,
        (5, 9): 5,
        (6, 4): 5,
        (6, 5): 1,
        (6, 6): 8,
        (6, 7): 7,
        (6, 8): 3,
        (6, 9): 9,
        (7, 4): 9,
        (7, 5): 4,
        (7, 6): 3,
        (7, 7): 6,
        (7, 8): 8,
        (7, 9): 1,
        (8, 4): 1,
        (8, 5): 6,
        (8, 6): 7,
        (8, 7): 5,
        (8, 8): 9,
        (8, 9): 2,
        (9, 4): 2,
        (9, 5): 8,
        (9, 6): 5,
        (9, 7): 4,
        (9, 8): 7,
    },
    "ex00.txt": {
        (1, 1): 5,
        (1, 2): 3,
        (1, 5): 7,
        (2, 1): 6,
        (2, 4): 1,
        (2, 5): 9,
        (2, 6): 5,
        (3, 2): 9,
        (3, 3): 8,
        (3, 8): 6,
        (4, 1): 8,
        (4, 5): 6,
        (4, 9): 3,
        (5, 1): 4,
        (5, 4): 8,
        (5, 6): 3,
        (5, 9): 1,
        (6, 1): 7,
        (6, 5): 2,
        (6, 9): 6,
        (7, 2): 6,
        (7, 7): 2,
        (7, 8): 8,
        (8, 4): 4,
        (8, 5): 1,
        (8, 6): 9,
        (8, 9): 5,
        (9, 5): 8,
        (9, 8): 7,
        (9, 9): 9,
    },
    "ex13.txt": {
        (1, 4): 8,
        (1, 5): 4,
        (1, 6): 3,
        (1, 7): 9,
        (1, 8): 7,
        (2, 3): 9,
        (2, 4): 2,
        (2, 5): 7,
        (2, 6): 1,
        (2, 7): 8,
        (2, 8): 5,
        (3, 3): 7,
        (3, 4): 9,
        (3, 5): 6,
        (3, 6): 5,
        (3, 7): 2,
        (3, 8): 1,
        (4, 3): 4,
        (4, 4): 7,
        (4, 5): 9,
        (4, 6): 8,
        (4, 7): 6,
        (4, 8): 3,
        (5, 3): 6,
        (5, 4): 3,
        (5, 5): 2,
        (5, 6): 4,
        (5, 7): 5,
        (5, 8): 8,
        (6, 3): 8,
        (6, 4): 1,
        (6, 5): 5,
        (6, 6): 6,
        (6, 7): 4,
        (6, 8): 9,
        (7, 3): 3,
        (7, 4): 6,
        (7, 5): 1,
        (7, 6): 9,
        (7, 7): 7,
        (7, 8): 2,
        (8, 3): 2,
        (8, 4): 4,
        (8, 5): 3,
        (8, 6): 7,
        (8, 7): 1,
        (9, 3): 1,
        (9, 4): 5,
        (9, 5): 8,
        (9, 6): 2,
        (9, 7): 3,
    },
    "ex07.txt": {
        (1, 3): 4,
        (1, 4): 5,
        (1, 5): 2,
        (1, 6): 9,
        (1, 7): 3,
        (2, 3): 8,
        (2, 4): 7,
        (2, 5): 3,
        (2, 6): 1,
        (2, 7): 9,
        (3, 3): 5,
        (3, 4): 8,
        (3, 5): 6,
        (3, 6): 4,
        (3, 7): 7,
        (4, 3): 3,
        (4, 4): 9,
        (4, 5): 7,
        (4, 6): 2,
        (4, 7): 6,
        (5, 1): 9,
        (5, 3): 6,
        (5, 4): 3,
        (5, 5): 4,
        (5, 6): 5,
        (5, 7): 1,
        (6, 1): 5,
        (6, 2): 4,
        (6, 3): 7,
        (6, 4): 1,
        (6, 5): 8,
        (6, 6): 6,
        (6, 7): 2,
        (7, 1): 4,
        (7, 2): 5,
        (7, 3): 2,
        (7, 4): 6,
        (7, 5): 1,
        (7, 6): 7,
        (8, 1): 8,
        (8, 2): 7,
        (8, 3): 1,
        (8, 4): 4,
        (8, 5): 9,
        (8, 6): 3,
        (9, 1): 6,
        (9, 2): 3,
        (9, 3): 9,
        (9, 4): 2,
        (9, 5): 5,
        (9, 6): 8,
    },
}


INITIAL = {
    "ex06.txt": [
        Function("", [Number(1), Number(3), Number(2)], True),
        Function("", [Number(1), Number(4), Number(7)], True),
        Function("", [Number(1), Number(5), Number(4)], True),
        Function("", [Number(1), Number(6), Number(9)], True),
        Function("", [Number(1), Number(7), Number(6)], True),
        Function("", [Number(1), Number(8), Number(8)], True),
        Function("", [Number(2), Number(3), Number(8)], True),
        Function("", [Number(2), Number(4), Number(6)], True),
        Function("", [Number(2), Number(5), Number(3)], True),
        Function("", [Number(2), Number(6), Number(1)], True),
        Function("", [Number(2), Number(7), Number(2)], True),
        Function("", [Number(2), Number(8), Number(7)], True),
        Function("", [Number(3), Number(3), Number(9)], True),
        Function("", [Number(3), Number(4), Number(5)], True),
        Function("", [Number(3), Number(5), Number(2)], True),
        Function("", [Number(3), Number(6), Number(8)], True),
        Function("", [Number(3), Number(7), Number(1)], True),
        Function("", [Number(3), Number(8), Number(3)], True),
        Function("", [Number(4), Number(3), Number(3)], True),
        Function("", [Number(4), Number(4), Number(4)], True),
        Function("", [Number(4), Number(5), Number(8)], True),
        Function("", [Number(4), Number(6), Number(7)], True),
        Function("", [Number(4), Number(7), Number(5)], True),
        Function("", [Number(4), Number(8), Number(6)], True),
        Function("", [Number(5), Number(1), Number(8)], True),
        Function("", [Number(5), Number(3), Number(4)], True),
        Function("", [Number(5), Number(4), Number(2)], True),
        Function("", [Number(5), Number(5), Number(6)], True),
        Function("", [Number(5), Number(6), Number(3)], True),
        Function("", [Number(5), Number(7), Number(7)], True),
        Function("", [Number(5), Number(8), Number(9)], True),
        Function("", [Number(6), Number(1), Number(2)], True),
        Function("", [Number(6), Number(2), Number(7)], True),
        Function("", [Number(6), Number(3), Number(6)], True),
        Function("", [Number(6), Number(4), Number(1)], True),
        Function("", [Number(6), Number(5), Number(9)], True),
        Function("", [Number(6), Number(6), Number(5)], True),
        Function("", [Number(6), Number(7), Number(8)], True),
        Function("", [Number(6), Number(8), Number(4)], True),
        Function("", [Number(7), Number(1), Number(4)], True),
        Function("", [Number(7), Number(2), Number(8)], True),
        Function("", [Number(7), Number(3), Number(5)], True),
        Function("", [Number(7), Number(4), Number(9)], True),
        Function("", [Number(7), Number(5), Number(7)], True),
        Function("", [Number(7), Number(6), Number(2)], True),
        Function("", [Number(7), Number(7), Number(3)], True),
        Function("", [Number(7), Number(8), Number(1)], True),
        Function("", [Number(8), Number(1), Number(6)], True),
        Function("", [Number(8), Number(2), Number(2)], True),
        Function("", [Number(8), Number(3), Number(7)], True),
        Function("", [Number(8), Number(4), Number(3)], True),
        Function("", [Number(8), Number(5), Number(1)], True),
        Function("", [Number(8), Number(6), Number(4)], True),
        Function("", [Number(8), Number(7), Number(9)], True),
        Function("", [Number(9), Number(1), Number(3)], True),
        Function("", [Number(9), Number(2), Number(9)], True),
        Function("", [Number(9), Number(3), Number(1)], True),
        Function("", [Number(9), Number(4), Number(8)], True),
        Function("", [Number(9), Number(5), Number(5)], True),
        Function("", [Number(9), Number(6), Number(6)], True),
        Function("", [Number(9), Number(7), Number(4)], True),
    ],
    "ex15.txt": [
        Function("", [Number(1), Number(4), Number(7)], True),
        Function("", [Number(1), Number(5), Number(1)], True),
        Function("", [Number(1), Number(6), Number(9)], True),
        Function("", [Number(1), Number(7), Number(5)], True),
        Function("", [Number(2), Number(3), Number(4)], True),
        Function("", [Number(2), Number(4), Number(3)], True),
        Function("", [Number(2), Number(5), Number(6)], True),
        Function("", [Number(2), Number(6), Number(2)], True),
        Function("", [Number(2), Number(7), Number(8)], True),
        Function("", [Number(3), Number(3), Number(9)], True),
        Function("", [Number(3), Number(4), Number(5)], True),
        Function("", [Number(3), Number(5), Number(8)], True),
        Function("", [Number(3), Number(6), Number(4)], True),
        Function("", [Number(3), Number(7), Number(1)], True),
        Function("", [Number(4), Number(3), Number(2)], True),
        Function("", [Number(4), Number(4), Number(1)], True),
        Function("", [Number(4), Number(5), Number(4)], True),
        Function("", [Number(4), Number(6), Number(7)], True),
        Function("", [Number(4), Number(7), Number(9)], True),
        Function("", [Number(5), Number(3), Number(5)], True),
        Function("", [Number(5), Number(4), Number(2)], True),
        Function("", [Number(5), Number(5), Number(9)], True),
        Function("", [Number(5), Number(6), Number(8)], True),
        Function("", [Number(5), Number(7), Number(3)], True),
        Function("", [Number(6), Number(3), Number(1)], True),
        Function("", [Number(6), Number(4), Number(6)], True),
        Function("", [Number(6), Number(5), Number(3)], True),
        Function("", [Number(6), Number(6), Number(5)], True),
        Function("", [Number(6), Number(7), Number(2)], True),
        Function("", [Number(7), Number(3), Number(7)], True),
        Function("", [Number(7), Number(4), Number(4)], True),
        Function("", [Number(7), Number(5), Number(2)], True),
        Function("", [Number(7), Number(6), Number(3)], True),
        Function("", [Number(8), Number(3), Number(3)], True),
        Function("", [Number(8), Number(4), Number(8)], True),
        Function("", [Number(8), Number(5), Number(7)], True),
        Function("", [Number(8), Number(6), Number(6)], True),
        Function("", [Number(9), Number(3), Number(6)], True),
        Function("", [Number(9), Number(4), Number(9)], True),
        Function("", [Number(9), Number(5), Number(5)], True),
        Function("", [Number(9), Number(6), Number(1)], True),
    ],
    "ex12.txt": [
        Function("", [Number(1), Number(4), Number(7)], True),
        Function("", [Number(1), Number(5), Number(5)], True),
        Function("", [Number(1), Number(6), Number(6)], True),
        Function("", [Number(1), Number(7), Number(8)], True),
        Function("", [Number(1), Number(8), Number(4)], True),
        Function("", [Number(2), Number(3), Number(4)], True),
        Function("", [Number(2), Number(4), Number(9)], True),
        Function("", [Number(2), Number(5), Number(8)], True),
        Function("", [Number(2), Number(6), Number(1)], True),
        Function("", [Number(2), Number(7), Number(2)], True),
        Function("", [Number(2), Number(8), Number(6)], True),
        Function("", [Number(3), Number(3), Number(6)], True),
        Function("", [Number(3), Number(4), Number(2)], True),
        Function("", [Number(3), Number(5), Number(3)], True),
        Function("", [Number(3), Number(6), Number(4)], True),
        Function("", [Number(3), Number(7), Number(5)], True),
        Function("", [Number(3), Number(8), Number(1)], True),
        Function("", [Number(4), Number(3), Number(3)], True),
        Function("", [Number(4), Number(4), Number(6)], True),
        Function("", [Number(4), Number(5), Number(9)], True),
        Function("", [Number(4), Number(6), Number(2)], True),
        Function("", [Number(4), Number(7), Number(4)], True),
        Function("", [Number(4), Number(8), Number(8)], True),
        Function("", [Number(5), Number(3), Number(2)], True),
        Function("", [Number(5), Number(4), Number(5)], True),
        Function("", [Number(5), Number(5), Number(4)], True),
        Function("", [Number(5), Number(6), Number(7)], True),
        Function("", [Number(5), Number(7), Number(3)], True),
        Function("", [Number(5), Number(8), Number(9)], True),
        Function("", [Number(6), Number(3), Number(5)], True),
        Function("", [Number(6), Number(4), Number(8)], True),
        Function("", [Number(6), Number(5), Number(1)], True),
        Function("", [Number(6), Number(6), Number(3)], True),
        Function("", [Number(6), Number(7), Number(7)], True),
        Function("", [Number(6), Number(8), Number(2)], True),
        Function("", [Number(7), Number(3), Number(8)], True),
        Function("", [Number(7), Number(4), Number(1)], True),
        Function("", [Number(7), Number(5), Number(6)], True),
        Function("", [Number(7), Number(6), Number(5)], True),
        Function("", [Number(7), Number(7), Number(9)], True),
        Function("", [Number(7), Number(8), Number(7)], True),
        Function("", [Number(8), Number(3), Number(7)], True),
        Function("", [Number(8), Number(4), Number(4)], True),
        Function("", [Number(8), Number(5), Number(2)], True),
        Function("", [Number(8), Number(6), Number(9)], True),
        Function("", [Number(8), Number(7), Number(6)], True),
        Function("", [Number(9), Number(3), Number(9)], True),
        Function("", [Number(9), Number(4), Number(3)], True),
        Function("", [Number(9), Number(5), Number(7)], True),
        Function("", [Number(9), Number(6), Number(8)], True),
        Function("", [Number(9), Number(7), Number(1)], True),
    ],
    "ex10.txt": [
        Function("", [Number(1), Number(4), Number(5)], True),
        Function("", [Number(1), Number(5), Number(2)], True),
        Function("", [Number(1), Number(6), Number(8)], True),
        Function("", [Number(1), Number(7), Number(9)], True),
        Function("", [Number(2), Number(3), Number(5)], True),
        Function("", [Number(2), Number(4), Number(7)], True),
        Function("", [Number(2), Number(5), Number(6)], True),
        Function("", [Number(2), Number(6), Number(3)], True),
        Function("", [Number(2), Number(7), Number(4)], True),
        Function("", [Number(3), Number(3), Number(8)], True),
        Function("", [Number(3), Number(4), Number(9)], True),
        Function("", [Number(3), Number(5), Number(4)], True),
        Function("", [Number(3), Number(6), Number(1)], True),
        Function("", [Number(3), Number(7), Number(3)], True),
        Function("", [Number(4), Number(3), Number(4)], True),
        Function("", [Number(4), Number(4), Number(8)], True),
        Function("", [Number(4), Number(5), Number(3)], True),
        Function("", [Number(4), Number(6), Number(5)], True),
        Function("", [Number(4), Number(7), Number(7)], True),
        Function("", [Number(5), Number(3), Number(7)], True),
        Function("", [Number(5), Number(4), Number(2)], True),
        Function("", [Number(5), Number(5), Number(9)], True),
        Function("", [Number(5), Number(6), Number(6)], True),
        Function("", [Number(5), Number(7), Number(1)], True),
        Function("", [Number(6), Number(3), Number(9)], True),
        Function("", [Number(6), Number(4), Number(4)], True),
        Function("", [Number(6), Number(5), Number(1)], True),
        Function("", [Number(6), Number(6), Number(7)], True),
        Function("", [Number(6), Number(7), Number(8)], True),
        Function("", [Number(7), Number(3), Number(3)], True),
        Function("", [Number(7), Number(4), Number(1)], True),
        Function("", [Number(7), Number(5), Number(8)], True),
        Function("", [Number(7), Number(6), Number(2)], True),
        Function("", [Number(8), Number(3), Number(2)], True),
        Function("", [Number(8), Number(4), Number(3)], True),
        Function("", [Number(8), Number(5), Number(7)], True),
        Function("", [Number(8), Number(6), Number(4)], True),
        Function("", [Number(9), Number(3), Number(1)], True),
        Function("", [Number(9), Number(4), Number(6)], True),
        Function("", [Number(9), Number(5), Number(5)], True),
        Function("", [Number(9), Number(6), Number(9)], True),
    ],
    "ex18.txt": [
        Function("", [Number(1), Number(5), Number(5)], True),
        Function("", [Number(1), Number(6), Number(2)], True),
        Function("", [Number(1), Number(7), Number(6)], True),
        Function("", [Number(1), Number(8), Number(9)], True),
        Function("", [Number(1), Number(9), Number(7)], True),
        Function("", [Number(2), Number(5), Number(6)], True),
        Function("", [Number(2), Number(6), Number(7)], True),
        Function("", [Number(2), Number(7), Number(4)], True),
        Function("", [Number(2), Number(8), Number(8)], True),
        Function("", [Number(2), Number(9), Number(3)], True),
        Function("", [Number(3), Number(4), Number(3)], True),
        Function("", [Number(3), Number(5), Number(4)], True),
        Function("", [Number(3), Number(6), Number(9)], True),
        Function("", [Number(3), Number(7), Number(2)], True),
        Function("", [Number(3), Number(8), Number(5)], True),
        Function("", [Number(3), Number(9), Number(1)], True),
        Function("", [Number(4), Number(4), Number(5)], True),
        Function("", [Number(4), Number(5), Number(3)], True),
        Function("", [Number(4), Number(6), Number(1)], True),
        Function("", [Number(4), Number(7), Number(8)], True),
        Function("", [Number(4), Number(8), Number(7)], True),
        Function("", [Number(4), Number(9), Number(9)], True),
        Function("", [Number(5), Number(4), Number(6)], True),
        Function("", [Number(5), Number(5), Number(2)], True),
        Function("", [Number(5), Number(6), Number(8)], True),
        Function("", [Number(5), Number(7), Number(5)], True),
        Function("", [Number(5), Number(8), Number(1)], True),
        Function("", [Number(5), Number(9), Number(4)], True),
        Function("", [Number(6), Number(4), Number(7)], True),
        Function("", [Number(6), Number(5), Number(9)], True),
        Function("", [Number(6), Number(6), Number(4)], True),
        Function("", [Number(6), Number(7), Number(3)], True),
        Function("", [Number(6), Number(8), Number(2)], True),
        Function("", [Number(6), Number(9), Number(6)], True),
        Function("", [Number(7), Number(4), Number(4)], True),
        Function("", [Number(7), Number(5), Number(7)], True),
        Function("", [Number(7), Number(6), Number(3)], True),
        Function("", [Number(7), Number(7), Number(1)], True),
        Function("", [Number(7), Number(8), Number(6)], True),
        Function("", [Number(7), Number(9), Number(5)], True),
        Function("", [Number(8), Number(4), Number(2)], True),
        Function("", [Number(8), Number(5), Number(1)], True),
        Function("", [Number(8), Number(6), Number(5)], True),
        Function("", [Number(8), Number(7), Number(9)], True),
        Function("", [Number(8), Number(8), Number(4)], True),
        Function("", [Number(8), Number(9), Number(8)], True),
        Function("", [Number(9), Number(4), Number(9)], True),
        Function("", [Number(9), Number(5), Number(8)], True),
        Function("", [Number(9), Number(6), Number(6)], True),
        Function("", [Number(9), Number(7), Number(7)], True),
        Function("", [Number(9), Number(8), Number(3)], True),
    ],
    "ex05.txt": [
        Function("", [Number(1), Number(5), Number(6)], True),
        Function("", [Number(1), Number(6), Number(2)], True),
        Function("", [Number(1), Number(7), Number(4)], True),
        Function("", [Number(1), Number(8), Number(8)], True),
        Function("", [Number(1), Number(9), Number(9)], True),
        Function("", [Number(2), Number(5), Number(4)], True),
        Function("", [Number(2), Number(6), Number(9)], True),
        Function("", [Number(2), Number(7), Number(1)], True),
        Function("", [Number(2), Number(8), Number(7)], True),
        Function("", [Number(2), Number(9), Number(5)], True),
        Function("", [Number(3), Number(4), Number(1)], True),
        Function("", [Number(3), Number(5), Number(8)], True),
        Function("", [Number(3), Number(6), Number(7)], True),
        Function("", [Number(3), Number(7), Number(6)], True),
        Function("", [Number(3), Number(8), Number(3)], True),
        Function("", [Number(3), Number(9), Number(2)], True),
        Function("", [Number(4), Number(4), Number(6)], True),
        Function("", [Number(4), Number(5), Number(3)], True),
        Function("", [Number(4), Number(6), Number(8)], True),
        Function("", [Number(4), Number(7), Number(9)], True),
        Function("", [Number(4), Number(8), Number(5)], True),
        Function("", [Number(4), Number(9), Number(1)], True),
        Function("", [Number(5), Number(4), Number(9)], True),
        Function("", [Number(5), Number(5), Number(2)], True),
        Function("", [Number(5), Number(6), Number(5)], True),
        Function("", [Number(5), Number(7), Number(8)], True),
        Function("", [Number(5), Number(8), Number(4)], True),
        Function("", [Number(5), Number(9), Number(7)], True),
        Function("", [Number(6), Number(4), Number(4)], True),
        Function("", [Number(6), Number(5), Number(7)], True),
        Function("", [Number(6), Number(6), Number(1)], True),
        Function("", [Number(6), Number(7), Number(3)], True),
        Function("", [Number(6), Number(8), Number(2)], True),
        Function("", [Number(6), Number(9), Number(6)], True),
        Function("", [Number(7), Number(4), Number(8)], True),
        Function("", [Number(7), Number(5), Number(9)], True),
        Function("", [Number(7), Number(6), Number(6)], True),
        Function("", [Number(7), Number(7), Number(7)], True),
        Function("", [Number(7), Number(8), Number(1)], True),
        Function("", [Number(7), Number(9), Number(3)], True),
        Function("", [Number(8), Number(4), Number(7)], True),
        Function("", [Number(8), Number(5), Number(5)], True),
        Function("", [Number(8), Number(6), Number(4)], True),
        Function("", [Number(8), Number(7), Number(2)], True),
        Function("", [Number(8), Number(8), Number(9)], True),
        Function("", [Number(8), Number(9), Number(8)], True),
        Function("", [Number(9), Number(4), Number(2)], True),
        Function("", [Number(9), Number(5), Number(1)], True),
        Function("", [Number(9), Number(6), Number(3)], True),
        Function("", [Number(9), Number(7), Number(5)], True),
        Function("", [Number(9), Number(8), Number(6)], True),
    ],
    "ex02.txt": [
        Function("", [Number(1), Number(3), Number(6)], True),
        Function("", [Number(1), Number(4), Number(2)], True),
        Function("", [Number(1), Number(5), Number(4)], True),
        Function("", [Number(1), Number(6), Number(8)], True),
        Function("", [Number(1), Number(7), Number(7)], True),
        Function("", [Number(2), Number(3), Number(2)], True),
        Function("", [Number(2), Number(4), Number(3)], True),
        Function("", [Number(2), Number(5), Number(7)], True),
        Function("", [Number(2), Number(6), Number(6)], True),
        Function("", [Number(2), Number(7), Number(8)], True),
        Function("", [Number(3), Number(3), Number(7)], True),
        Function("", [Number(3), Number(4), Number(1)], True),
        Function("", [Number(3), Number(5), Number(9)], True),
        Function("", [Number(3), Number(6), Number(5)], True),
        Function("", [Number(3), Number(7), Number(2)], True),
        Function("", [Number(4), Number(3), Number(4)], True),
        Function("", [Number(4), Number(4), Number(7)], True),
        Function("", [Number(4), Number(5), Number(5)], True),
        Function("", [Number(4), Number(6), Number(3)], True),
        Function("", [Number(4), Number(7), Number(1)], True),
        Function("", [Number(5), Number(1), Number(7)], True),
        Function("", [Number(5), Number(3), Number(8)], True),
        Function("", [Number(5), Number(4), Number(4)], True),
        Function("", [Number(5), Number(5), Number(2)], True),
        Function("", [Number(5), Number(6), Number(9)], True),
        Function("", [Number(5), Number(7), Number(3)], True),
        Function("", [Number(6), Number(1), Number(3)], True),
        Function("", [Number(6), Number(2), Number(9)], True),
        Function("", [Number(6), Number(3), Number(5)], True),
        Function("", [Number(6), Number(4), Number(6)], True),
        Function("", [Number(6), Number(5), Number(8)], True),
        Function("", [Number(6), Number(6), Number(1)], True),
        Function("", [Number(6), Number(7), Number(4)], True),
        Function("", [Number(7), Number(1), Number(2)], True),
        Function("", [Number(7), Number(2), Number(6)], True),
        Function("", [Number(7), Number(3), Number(9)], True),
        Function("", [Number(7), Number(4), Number(8)], True),
        Function("", [Number(7), Number(5), Number(3)], True),
        Function("", [Number(7), Number(6), Number(4)], True),
        Function("", [Number(8), Number(1), Number(4)], True),
        Function("", [Number(8), Number(2), Number(8)], True),
        Function("", [Number(8), Number(3), Number(1)], True),
        Function("", [Number(8), Number(4), Number(5)], True),
        Function("", [Number(8), Number(5), Number(6)], True),
        Function("", [Number(8), Number(6), Number(7)], True),
        Function("", [Number(9), Number(1), Number(5)], True),
        Function("", [Number(9), Number(2), Number(7)], True),
        Function("", [Number(9), Number(3), Number(3)], True),
        Function("", [Number(9), Number(4), Number(9)], True),
        Function("", [Number(9), Number(5), Number(1)], True),
        Function("", [Number(9), Number(6), Number(2)], True),
    ],
    "ex17.txt": [
        Function("", [Number(1), Number(5), Number(7)], True),
        Function("", [Number(1), Number(6), Number(9)], True),
        Function("", [Number(1), Number(7), Number(3)], True),
        Function("", [Number(1), Number(8), Number(2)], True),
        Function("", [Number(1), Number(9), Number(6)], True),
        Function("", [Number(2), Number(5), Number(3)], True),
        Function("", [Number(2), Number(6), Number(2)], True),
        Function("", [Number(2), Number(7), Number(8)], True),
        Function("", [Number(2), Number(8), Number(4)], True),
        Function("", [Number(2), Number(9), Number(1)], True),
        Function("", [Number(3), Number(4), Number(1)], True),
        Function("", [Number(3), Number(5), Number(8)], True),
        Function("", [Number(3), Number(6), Number(4)], True),
        Function("", [Number(3), Number(7), Number(5)], True),
        Function("", [Number(3), Number(8), Number(9)], True),
        Function("", [Number(3), Number(9), Number(7)], True),
        Function("", [Number(4), Number(4), Number(2)], True),
        Function("", [Number(4), Number(5), Number(4)], True),
        Function("", [Number(4), Number(6), Number(5)], True),
        Function("", [Number(4), Number(7), Number(1)], True),
        Function("", [Number(4), Number(8), Number(8)], True),
        Function("", [Number(5), Number(4), Number(8)], True),
        Function("", [Number(5), Number(5), Number(6)], True),
        Function("", [Number(5), Number(6), Number(1)], True),
        Function("", [Number(5), Number(7), Number(7)], True),
        Function("", [Number(5), Number(8), Number(5)], True),
        Function("", [Number(6), Number(4), Number(7)], True),
        Function("", [Number(6), Number(5), Number(9)], True),
        Function("", [Number(6), Number(6), Number(3)], True),
        Function("", [Number(6), Number(7), Number(4)], True),
        Function("", [Number(6), Number(8), Number(6)], True),
        Function("", [Number(7), Number(4), Number(4)], True),
        Function("", [Number(7), Number(5), Number(1)], True),
        Function("", [Number(7), Number(6), Number(8)], True),
        Function("", [Number(7), Number(7), Number(2)], True),
        Function("", [Number(7), Number(8), Number(3)], True),
        Function("", [Number(8), Number(4), Number(3)], True),
        Function("", [Number(8), Number(5), Number(5)], True),
        Function("", [Number(8), Number(6), Number(6)], True),
        Function("", [Number(8), Number(7), Number(9)], True),
        Function("", [Number(8), Number(8), Number(7)], True),
        Function("", [Number(9), Number(4), Number(9)], True),
        Function("", [Number(9), Number(5), Number(2)], True),
        Function("", [Number(9), Number(6), Number(7)], True),
        Function("", [Number(9), Number(7), Number(6)], True),
        Function("", [Number(9), Number(8), Number(1)], True),
    ],
    "ex16.txt": [
        Function("", [Number(1), Number(4), Number(7)], True),
        Function("", [Number(1), Number(5), Number(2)], True),
        Function("", [Number(1), Number(6), Number(6)], True),
        Function("", [Number(1), Number(7), Number(4)], True),
        Function("", [Number(2), Number(3), Number(9)], True),
        Function("", [Number(2), Number(4), Number(1)], True),
        Function("", [Number(2), Number(5), Number(8)], True),
        Function("", [Number(2), Number(6), Number(3)], True),
        Function("", [Number(2), Number(7), Number(2)], True),
        Function("", [Number(3), Number(3), Number(6)], True),
        Function("", [Number(3), Number(4), Number(4)], True),
        Function("", [Number(3), Number(5), Number(5)], True),
        Function("", [Number(3), Number(6), Number(9)], True),
        Function("", [Number(3), Number(7), Number(3)], True),
        Function("", [Number(4), Number(3), Number(2)], True),
        Function("", [Number(4), Number(4), Number(9)], True),
        Function("", [Number(4), Number(5), Number(1)], True),
        Function("", [Number(4), Number(6), Number(7)], True),
        Function("", [Number(4), Number(7), Number(8)], True),
        Function("", [Number(5), Number(3), Number(5)], True),
        Function("", [Number(5), Number(4), Number(2)], True),
        Function("", [Number(5), Number(5), Number(3)], True),
        Function("", [Number(5), Number(6), Number(4)], True),
        Function("", [Number(5), Number(7), Number(9)], True),
        Function("", [Number(6), Number(3), Number(7)], True),
        Function("", [Number(6), Number(4), Number(5)], True),
        Function("", [Number(6), Number(5), Number(6)], True),
        Function("", [Number(6), Number(6), Number(8)], True),
        Function("", [Number(6), Number(7), Number(1)], True),
        Function("", [Number(7), Number(3), Number(4)], True),
        Function("", [Number(7), Number(4), Number(3)], True),
        Function("", [Number(7), Number(5), Number(9)], True),
        Function("", [Number(7), Number(6), Number(2)], True),
        Function("", [Number(8), Number(3), Number(1)], True),
        Function("", [Number(8), Number(4), Number(8)], True),
        Function("", [Number(8), Number(5), Number(4)], True),
        Function("", [Number(8), Number(6), Number(5)], True),
        Function("", [Number(9), Number(3), Number(3)], True),
        Function("", [Number(9), Number(4), Number(6)], True),
        Function("", [Number(9), Number(5), Number(7)], True),
        Function("", [Number(9), Number(6), Number(1)], True),
    ],
    "ex08.txt": [
        Function("", [Number(1), Number(3), Number(4)], True),
        Function("", [Number(1), Number(4), Number(9)], True),
        Function("", [Number(1), Number(5), Number(8)], True),
        Function("", [Number(1), Number(6), Number(6)], True),
        Function("", [Number(1), Number(7), Number(2)], True),
        Function("", [Number(2), Number(3), Number(8)], True),
        Function("", [Number(2), Number(4), Number(2)], True),
        Function("", [Number(2), Number(5), Number(7)], True),
        Function("", [Number(2), Number(6), Number(4)], True),
        Function("", [Number(2), Number(7), Number(1)], True),
        Function("", [Number(3), Number(3), Number(7)], True),
        Function("", [Number(3), Number(4), Number(5)], True),
        Function("", [Number(3), Number(5), Number(1)], True),
        Function("", [Number(3), Number(6), Number(3)], True),
        Function("", [Number(3), Number(7), Number(6)], True),
        Function("", [Number(4), Number(3), Number(6)], True),
        Function("", [Number(4), Number(4), Number(1)], True),
        Function("", [Number(4), Number(5), Number(4)], True),
        Function("", [Number(4), Number(6), Number(8)], True),
        Function("", [Number(4), Number(7), Number(3)], True),
        Function("", [Number(5), Number(2), Number(8)], True),
        Function("", [Number(5), Number(3), Number(1)], True),
        Function("", [Number(5), Number(4), Number(3)], True),
        Function("", [Number(5), Number(5), Number(9)], True),
        Function("", [Number(5), Number(6), Number(2)], True),
        Function("", [Number(5), Number(7), Number(5)], True),
        Function("", [Number(6), Number(1), Number(2)], True),
        Function("", [Number(6), Number(2), Number(4)], True),
        Function("", [Number(6), Number(3), Number(3)], True),
        Function("", [Number(6), Number(4), Number(6)], True),
        Function("", [Number(6), Number(5), Number(5)], True),
        Function("", [Number(6), Number(6), Number(7)], True),
        Function("", [Number(6), Number(7), Number(9)], True),
        Function("", [Number(7), Number(1), Number(8)], True),
        Function("", [Number(7), Number(2), Number(1)], True),
        Function("", [Number(7), Number(3), Number(5)], True),
        Function("", [Number(7), Number(4), Number(7)], True),
        Function("", [Number(7), Number(5), Number(2)], True),
        Function("", [Number(7), Number(6), Number(9)], True),
        Function("", [Number(8), Number(1), Number(4)], True),
        Function("", [Number(8), Number(2), Number(3)], True),
        Function("", [Number(8), Number(3), Number(9)], True),
        Function("", [Number(8), Number(4), Number(8)], True),
        Function("", [Number(8), Number(5), Number(6)], True),
        Function("", [Number(8), Number(6), Number(5)], True),
        Function("", [Number(9), Number(1), Number(6)], True),
        Function("", [Number(9), Number(2), Number(7)], True),
        Function("", [Number(9), Number(3), Number(2)], True),
        Function("", [Number(9), Number(4), Number(4)], True),
        Function("", [Number(9), Number(5), Number(3)], True),
        Function("", [Number(9), Number(6), Number(1)], True),
    ],
    "ex01.txt": [
        Function("", [Number(1), Number(4), Number(5)], True),
        Function("", [Number(1), Number(5), Number(4)], True),
        Function("", [Number(1), Number(6), Number(9)], True),
        Function("", [Number(1), Number(7), Number(2)], True),
        Function("", [Number(1), Number(8), Number(8)], True),
        Function("", [Number(1), Number(9), Number(3)], True),
        Function("", [Number(2), Number(3), Number(3)], True),
        Function("", [Number(2), Number(4), Number(7)], True),
        Function("", [Number(2), Number(5), Number(1)], True),
        Function("", [Number(2), Number(6), Number(8)], True),
        Function("", [Number(2), Number(7), Number(5)], True),
        Function("", [Number(2), Number(8), Number(6)], True),
        Function("", [Number(2), Number(9), Number(9)], True),
        Function("", [Number(3), Number(3), Number(8)], True),
        Function("", [Number(3), Number(4), Number(2)], True),
        Function("", [Number(3), Number(5), Number(3)], True),
        Function("", [Number(3), Number(6), Number(6)], True),
        Function("", [Number(3), Number(7), Number(1)], True),
        Function("", [Number(3), Number(8), Number(4)], True),
        Function("", [Number(3), Number(9), Number(7)], True),
        Function("", [Number(4), Number(3), Number(1)], True),
        Function("", [Number(4), Number(4), Number(8)], True),
        Function("", [Number(4), Number(5), Number(9)], True),
        Function("", [Number(4), Number(6), Number(5)], True),
        Function("", [Number(4), Number(7), Number(6)], True),
        Function("", [Number(4), Number(8), Number(2)], True),
        Function("", [Number(4), Number(9), Number(4)], True),
        Function("", [Number(5), Number(3), Number(4)], True),
        Function("", [Number(5), Number(4), Number(1)], True),
        Function("", [Number(5), Number(5), Number(6)], True),
        Function("", [Number(5), Number(6), Number(7)], True),
        Function("", [Number(5), Number(7), Number(3)], True),
        Function("", [Number(5), Number(8), Number(9)], True),
        Function("", [Number(5), Number(9), Number(5)], True),
        Function("", [Number(6), Number(3), Number(6)], True),
        Function("", [Number(6), Number(4), Number(3)], True),
        Function("", [Number(6), Number(5), Number(2)], True),
        Function("", [Number(6), Number(6), Number(4)], True),
        Function("", [Number(6), Number(7), Number(8)], True),
        Function("", [Number(6), Number(8), Number(7)], True),
        Function("", [Number(6), Number(9), Number(1)], True),
        Function("", [Number(7), Number(3), Number(5)], True),
        Function("", [Number(7), Number(4), Number(9)], True),
        Function("", [Number(7), Number(5), Number(7)], True),
        Function("", [Number(7), Number(6), Number(2)], True),
        Function("", [Number(7), Number(7), Number(4)], True),
        Function("", [Number(7), Number(8), Number(1)], True),
        Function("", [Number(7), Number(9), Number(8)], True),
        Function("", [Number(8), Number(3), Number(9)], True),
        Function("", [Number(8), Number(4), Number(6)], True),
        Function("", [Number(8), Number(5), Number(5)], True),
        Function("", [Number(8), Number(6), Number(1)], True),
        Function("", [Number(8), Number(7), Number(7)], True),
        Function("", [Number(8), Number(8), Number(3)], True),
        Function("", [Number(8), Number(9), Number(2)], True),
        Function("", [Number(9), Number(3), Number(2)], True),
        Function("", [Number(9), Number(4), Number(4)], True),
        Function("", [Number(9), Number(5), Number(8)], True),
        Function("", [Number(9), Number(6), Number(3)], True),
        Function("", [Number(9), Number(7), Number(9)], True),
        Function("", [Number(9), Number(8), Number(5)], True),
    ],
    "ex04.txt": [
        Function("", [Number(1), Number(4), Number(3)], True),
        Function("", [Number(1), Number(5), Number(4)], True),
        Function("", [Number(1), Number(6), Number(8)], True),
        Function("", [Number(1), Number(7), Number(5)], True),
        Function("", [Number(2), Number(3), Number(7)], True),
        Function("", [Number(2), Number(4), Number(6)], True),
        Function("", [Number(2), Number(5), Number(1)], True),
        Function("", [Number(2), Number(6), Number(9)], True),
        Function("", [Number(2), Number(7), Number(8)], True),
        Function("", [Number(3), Number(3), Number(6)], True),
        Function("", [Number(3), Number(4), Number(2)], True),
        Function("", [Number(3), Number(5), Number(5)], True),
        Function("", [Number(3), Number(6), Number(7)], True),
        Function("", [Number(3), Number(7), Number(1)], True),
        Function("", [Number(4), Number(3), Number(5)], True),
        Function("", [Number(4), Number(4), Number(4)], True),
        Function("", [Number(4), Number(5), Number(9)], True),
        Function("", [Number(4), Number(6), Number(1)], True),
        Function("", [Number(4), Number(7), Number(6)], True),
        Function("", [Number(5), Number(3), Number(1)], True),
        Function("", [Number(5), Number(4), Number(8)], True),
        Function("", [Number(5), Number(5), Number(6)], True),
        Function("", [Number(5), Number(6), Number(3)], True),
        Function("", [Number(5), Number(7), Number(4)], True),
        Function("", [Number(6), Number(3), Number(8)], True),
        Function("", [Number(6), Number(4), Number(5)], True),
        Function("", [Number(6), Number(5), Number(7)], True),
        Function("", [Number(6), Number(6), Number(2)], True),
        Function("", [Number(6), Number(7), Number(3)], True),
        Function("", [Number(7), Number(3), Number(3)], True),
        Function("", [Number(7), Number(4), Number(1)], True),
        Function("", [Number(7), Number(5), Number(8)], True),
        Function("", [Number(7), Number(6), Number(4)], True),
        Function("", [Number(8), Number(3), Number(2)], True),
        Function("", [Number(8), Number(4), Number(9)], True),
        Function("", [Number(8), Number(5), Number(3)], True),
        Function("", [Number(8), Number(6), Number(5)], True),
        Function("", [Number(9), Number(3), Number(4)], True),
        Function("", [Number(9), Number(4), Number(7)], True),
        Function("", [Number(9), Number(5), Number(2)], True),
        Function("", [Number(9), Number(6), Number(6)], True),
    ],
    "ex14.txt": [
        Function("", [Number(1), Number(4), Number(1)], True),
        Function("", [Number(1), Number(5), Number(2)], True),
        Function("", [Number(1), Number(6), Number(8)], True),
        Function("", [Number(1), Number(7), Number(4)], True),
        Function("", [Number(2), Number(3), Number(4)], True),
        Function("", [Number(2), Number(4), Number(5)], True),
        Function("", [Number(2), Number(5), Number(6)], True),
        Function("", [Number(2), Number(6), Number(9)], True),
        Function("", [Number(2), Number(7), Number(2)], True),
        Function("", [Number(3), Number(3), Number(6)], True),
        Function("", [Number(3), Number(4), Number(7)], True),
        Function("", [Number(3), Number(5), Number(4)], True),
        Function("", [Number(3), Number(6), Number(3)], True),
        Function("", [Number(3), Number(7), Number(1)], True),
        Function("", [Number(4), Number(3), Number(2)], True),
        Function("", [Number(4), Number(4), Number(4)], True),
        Function("", [Number(4), Number(5), Number(8)], True),
        Function("", [Number(4), Number(6), Number(5)], True),
        Function("", [Number(4), Number(7), Number(6)], True),
        Function("", [Number(5), Number(3), Number(8)], True),
        Function("", [Number(5), Number(4), Number(2)], True),
        Function("", [Number(5), Number(5), Number(3)], True),
        Function("", [Number(5), Number(6), Number(7)], True),
        Function("", [Number(5), Number(7), Number(9)], True),
        Function("", [Number(6), Number(3), Number(7)], True),
        Function("", [Number(6), Number(4), Number(9)], True),
        Function("", [Number(6), Number(5), Number(1)], True),
        Function("", [Number(6), Number(6), Number(6)], True),
        Function("", [Number(6), Number(7), Number(5)], True),
        Function("", [Number(7), Number(3), Number(1)], True),
        Function("", [Number(7), Number(4), Number(6)], True),
        Function("", [Number(7), Number(5), Number(7)], True),
        Function("", [Number(7), Number(6), Number(4)], True),
        Function("", [Number(8), Number(3), Number(5)], True),
        Function("", [Number(8), Number(4), Number(3)], True),
        Function("", [Number(8), Number(5), Number(9)], True),
        Function("", [Number(8), Number(6), Number(1)], True),
        Function("", [Number(9), Number(3), Number(3)], True),
        Function("", [Number(9), Number(4), Number(8)], True),
        Function("", [Number(9), Number(5), Number(5)], True),
        Function("", [Number(9), Number(6), Number(2)], True),
    ],
    "ex09.txt": [
        Function("", [Number(1), Number(3), Number(9)], True),
        Function("", [Number(1), Number(4), Number(3)], True),
        Function("", [Number(1), Number(5), Number(5)], True),
        Function("", [Number(1), Number(6), Number(4)], True),
        Function("", [Number(1), Number(7), Number(8)], True),
        Function("", [Number(2), Number(3), Number(7)], True),
        Function("", [Number(2), Number(4), Number(2)], True),
        Function("", [Number(2), Number(5), Number(8)], True),
        Function("", [Number(2), Number(6), Number(6)], True),
        Function("", [Number(2), Number(7), Number(4)], True),
        Function("", [Number(3), Number(3), Number(4)], True),
        Function("", [Number(3), Number(4), Number(9)], True),
        Function("", [Number(3), Number(5), Number(7)], True),
        Function("", [Number(3), Number(6), Number(1)], True),
        Function("", [Number(3), Number(7), Number(2)], True),
        Function("", [Number(4), Number(3), Number(5)], True),
        Function("", [Number(4), Number(4), Number(7)], True),
        Function("", [Number(4), Number(5), Number(6)], True),
        Function("", [Number(4), Number(6), Number(8)], True),
        Function("", [Number(4), Number(7), Number(9)], True),
        Function("", [Number(5), Number(2), Number(9)], True),
        Function("", [Number(5), Number(3), Number(6)], True),
        Function("", [Number(5), Number(4), Number(4)], True),
        Function("", [Number(5), Number(5), Number(1)], True),
        Function("", [Number(5), Number(6), Number(3)], True),
        Function("", [Number(5), Number(7), Number(5)], True),
        Function("", [Number(6), Number(1), Number(8)], True),
        Function("", [Number(6), Number(2), Number(7)], True),
        Function("", [Number(6), Number(3), Number(3)], True),
        Function("", [Number(6), Number(4), Number(5)], True),
        Function("", [Number(6), Number(5), Number(2)], True),
        Function("", [Number(6), Number(6), Number(9)], True),
        Function("", [Number(6), Number(7), Number(6)], True),
        Function("", [Number(7), Number(1), Number(9)], True),
        Function("", [Number(7), Number(2), Number(6)], True),
        Function("", [Number(7), Number(3), Number(1)], True),
        Function("", [Number(7), Number(4), Number(8)], True),
        Function("", [Number(7), Number(5), Number(3)], True),
        Function("", [Number(7), Number(6), Number(2)], True),
        Function("", [Number(8), Number(1), Number(7)], True),
        Function("", [Number(8), Number(2), Number(4)], True),
        Function("", [Number(8), Number(3), Number(2)], True),
        Function("", [Number(8), Number(4), Number(1)], True),
        Function("", [Number(8), Number(5), Number(9)], True),
        Function("", [Number(8), Number(6), Number(5)], True),
        Function("", [Number(9), Number(1), Number(5)], True),
        Function("", [Number(9), Number(2), Number(3)], True),
        Function("", [Number(9), Number(3), Number(8)], True),
        Function("", [Number(9), Number(4), Number(6)], True),
        Function("", [Number(9), Number(5), Number(4)], True),
        Function("", [Number(9), Number(6), Number(7)], True),
    ],
    "ex11.txt": [
        Function("", [Number(1), Number(3), Number(9)], True),
        Function("", [Number(1), Number(4), Number(8)], True),
        Function("", [Number(1), Number(5), Number(6)], True),
        Function("", [Number(1), Number(6), Number(4)], True),
        Function("", [Number(1), Number(7), Number(7)], True),
        Function("", [Number(2), Number(3), Number(3)], True),
        Function("", [Number(2), Number(4), Number(7)], True),
        Function("", [Number(2), Number(5), Number(9)], True),
        Function("", [Number(2), Number(6), Number(1)], True),
        Function("", [Number(2), Number(7), Number(4)], True),
        Function("", [Number(3), Number(3), Number(4)], True),
        Function("", [Number(3), Number(4), Number(3)], True),
        Function("", [Number(3), Number(5), Number(5)], True),
        Function("", [Number(3), Number(6), Number(2)], True),
        Function("", [Number(3), Number(7), Number(8)], True),
        Function("", [Number(4), Number(3), Number(2)], True),
        Function("", [Number(4), Number(4), Number(1)], True),
        Function("", [Number(4), Number(5), Number(4)], True),
        Function("", [Number(4), Number(6), Number(7)], True),
        Function("", [Number(4), Number(7), Number(6)], True),
        Function("", [Number(5), Number(1), Number(7)], True),
        Function("", [Number(5), Number(3), Number(6)], True),
        Function("", [Number(5), Number(4), Number(9)], True),
        Function("", [Number(5), Number(5), Number(8)], True),
        Function("", [Number(5), Number(6), Number(5)], True),
        Function("", [Number(5), Number(7), Number(1)], True),
        Function("", [Number(6), Number(1), Number(5)], True),
        Function("", [Number(6), Number(2), Number(1)], True),
        Function("", [Number(6), Number(3), Number(8)], True),
        Function("", [Number(6), Number(4), Number(6)], True),
        Function("", [Number(6), Number(5), Number(2)], True),
        Function("", [Number(6), Number(6), Number(3)], True),
        Function("", [Number(6), Number(7), Number(9)], True),
        Function("", [Number(7), Number(1), Number(2)], True),
        Function("", [Number(7), Number(2), Number(6)], True),
        Function("", [Number(7), Number(3), Number(5)], True),
        Function("", [Number(7), Number(4), Number(4)], True),
        Function("", [Number(7), Number(5), Number(1)], True),
        Function("", [Number(7), Number(6), Number(8)], True),
        Function("", [Number(8), Number(1), Number(9)], True),
        Function("", [Number(8), Number(2), Number(8)], True),
        Function("", [Number(8), Number(3), Number(7)], True),
        Function("", [Number(8), Number(4), Number(2)], True),
        Function("", [Number(8), Number(5), Number(3)], True),
        Function("", [Number(8), Number(6), Number(6)], True),
        Function("", [Number(9), Number(1), Number(4)], True),
        Function("", [Number(9), Number(2), Number(3)], True),
        Function("", [Number(9), Number(3), Number(1)], True),
        Function("", [Number(9), Number(4), Number(5)], True),
        Function("", [Number(9), Number(5), Number(7)], True),
        Function("", [Number(9), Number(6), Number(9)], True),
    ],
    "ex03.txt": [
        Function("", [Number(1), Number(5), Number(9)], True),
        Function("", [Number(1), Number(6), Number(4)], True),
        Function("", [Number(1), Number(7), Number(3)], True),
        Function("", [Number(1), Number(8), Number(5)], True),
        Function("", [Number(1), Number(9), Number(7)], True),
        Function("", [Number(2), Number(5), Number(2)], True),
        Function("", [Number(2), Number(6), Number(6)], True),
        Function("", [Number(2), Number(7), Number(9)], True),
        Function("", [Number(2), Number(8), Number(1)], True),
        Function("", [Number(2), Number(9), Number(4)], True),
        Function("", [Number(3), Number(4), Number(3)], True),
        Function("", [Number(3), Number(5), Number(5)], True),
        Function("", [Number(3), Number(6), Number(1)], True),
        Function("", [Number(3), Number(7), Number(8)], True),
        Function("", [Number(3), Number(8), Number(2)], True),
        Function("", [Number(3), Number(9), Number(6)], True),
        Function("", [Number(4), Number(4), Number(4)], True),
        Function("", [Number(4), Number(5), Number(3)], True),
        Function("", [Number(4), Number(6), Number(2)], True),
        Function("", [Number(4), Number(7), Number(1)], True),
        Function("", [Number(4), Number(8), Number(6)], True),
        Function("", [Number(4), Number(9), Number(8)], True),
        Function("", [Number(5), Number(4), Number(6)], True),
        Function("", [Number(5), Number(5), Number(7)], True),
        Function("", [Number(5), Number(6), Number(9)], True),
        Function("", [Number(5), Number(7), Number(2)], True),
        Function("", [Number(5), Number(8), Number(4)], True),
        Function("", [Number(5), Number(9), Number(5)], True),
        Function("", [Number(6), Number(4), Number(5)], True),
        Function("", [Number(6), Number(5), Number(1)], True),
        Function("", [Number(6), Number(6), Number(8)], True),
        Function("", [Number(6), Number(7), Number(7)], True),
        Function("", [Number(6), Number(8), Number(3)], True),
        Function("", [Number(6), Number(9), Number(9)], True),
        Function("", [Number(7), Number(4), Number(9)], True),
        Function("", [Number(7), Number(5), Number(4)], True),
        Function("", [Number(7), Number(6), Number(3)], True),
        Function("", [Number(7), Number(7), Number(6)], True),
        Function("", [Number(7), Number(8), Number(8)], True),
        Function("", [Number(7), Number(9), Number(1)], True),
        Function("", [Number(8), Number(4), Number(1)], True),
        Function("", [Number(8), Number(5), Number(6)], True),
        Function("", [Number(8), Number(6), Number(7)], True),
        Function("", [Number(8), Number(7), Number(5)], True),
        Function("", [Number(8), Number(8), Number(9)], True),
        Function("", [Number(8), Number(9), Number(2)], True),
        Function("", [Number(9), Number(4), Number(2)], True),
        Function("", [Number(9), Number(5), Number(8)], True),
        Function("", [Number(9), Number(6), Number(5)], True),
        Function("", [Number(9), Number(7), Number(4)], True),
        Function("", [Number(9), Number(8), Number(7)], True),
    ],
    "ex00.txt": [
        Function("", [Number(1), Number(1), Number(5)], True),
        Function("", [Number(1), Number(2), Number(3)], True),
        Function("", [Number(1), Number(5), Number(7)], True),
        Function("", [Number(2), Number(1), Number(6)], True),
        Function("", [Number(2), Number(4), Number(1)], True),
        Function("", [Number(2), Number(5), Number(9)], True),
        Function("", [Number(2), Number(6), Number(5)], True),
        Function("", [Number(3), Number(2), Number(9)], True),
        Function("", [Number(3), Number(3), Number(8)], True),
        Function("", [Number(3), Number(8), Number(6)], True),
        Function("", [Number(4), Number(1), Number(8)], True),
        Function("", [Number(4), Number(5), Number(6)], True),
        Function("", [Number(4), Number(9), Number(3)], True),
        Function("", [Number(5), Number(1), Number(4)], True),
        Function("", [Number(5), Number(4), Number(8)], True),
        Function("", [Number(5), Number(6), Number(3)], True),
        Function("", [Number(5), Number(9), Number(1)], True),
        Function("", [Number(6), Number(1), Number(7)], True),
        Function("", [Number(6), Number(5), Number(2)], True),
        Function("", [Number(6), Number(9), Number(6)], True),
        Function("", [Number(7), Number(2), Number(6)], True),
        Function("", [Number(7), Number(7), Number(2)], True),
        Function("", [Number(7), Number(8), Number(8)], True),
        Function("", [Number(8), Number(4), Number(4)], True),
        Function("", [Number(8), Number(5), Number(1)], True),
        Function("", [Number(8), Number(6), Number(9)], True),
        Function("", [Number(8), Number(9), Number(5)], True),
        Function("", [Number(9), Number(5), Number(8)], True),
        Function("", [Number(9), Number(8), Number(7)], True),
        Function("", [Number(9), Number(9), Number(9)], True),
    ],
    "ex13.txt": [
        Function("", [Number(1), Number(4), Number(8)], True),
        Function("", [Number(1), Number(5), Number(4)], True),
        Function("", [Number(1), Number(6), Number(3)], True),
        Function("", [Number(1), Number(7), Number(9)], True),
        Function("", [Number(1), Number(8), Number(7)], True),
        Function("", [Number(2), Number(3), Number(9)], True),
        Function("", [Number(2), Number(4), Number(2)], True),
        Function("", [Number(2), Number(5), Number(7)], True),
        Function("", [Number(2), Number(6), Number(1)], True),
        Function("", [Number(2), Number(7), Number(8)], True),
        Function("", [Number(2), Number(8), Number(5)], True),
        Function("", [Number(3), Number(3), Number(7)], True),
        Function("", [Number(3), Number(4), Number(9)], True),
        Function("", [Number(3), Number(5), Number(6)], True),
        Function("", [Number(3), Number(6), Number(5)], True),
        Function("", [Number(3), Number(7), Number(2)], True),
        Function("", [Number(3), Number(8), Number(1)], True),
        Function("", [Number(4), Number(3), Number(4)], True),
        Function("", [Number(4), Number(4), Number(7)], True),
        Function("", [Number(4), Number(5), Number(9)], True),
        Function("", [Number(4), Number(6), Number(8)], True),
        Function("", [Number(4), Number(7), Number(6)], True),
        Function("", [Number(4), Number(8), Number(3)], True),
        Function("", [Number(5), Number(3), Number(6)], True),
        Function("", [Number(5), Number(4), Number(3)], True),
        Function("", [Number(5), Number(5), Number(2)], True),
        Function("", [Number(5), Number(6), Number(4)], True),
        Function("", [Number(5), Number(7), Number(5)], True),
        Function("", [Number(5), Number(8), Number(8)], True),
        Function("", [Number(6), Number(3), Number(8)], True),
        Function("", [Number(6), Number(4), Number(1)], True),
        Function("", [Number(6), Number(5), Number(5)], True),
        Function("", [Number(6), Number(6), Number(6)], True),
        Function("", [Number(6), Number(7), Number(4)], True),
        Function("", [Number(6), Number(8), Number(9)], True),
        Function("", [Number(7), Number(3), Number(3)], True),
        Function("", [Number(7), Number(4), Number(6)], True),
        Function("", [Number(7), Number(5), Number(1)], True),
        Function("", [Number(7), Number(6), Number(9)], True),
        Function("", [Number(7), Number(7), Number(7)], True),
        Function("", [Number(7), Number(8), Number(2)], True),
        Function("", [Number(8), Number(3), Number(2)], True),
        Function("", [Number(8), Number(4), Number(4)], True),
        Function("", [Number(8), Number(5), Number(3)], True),
        Function("", [Number(8), Number(6), Number(7)], True),
        Function("", [Number(8), Number(7), Number(1)], True),
        Function("", [Number(9), Number(3), Number(1)], True),
        Function("", [Number(9), Number(4), Number(5)], True),
        Function("", [Number(9), Number(5), Number(8)], True),
        Function("", [Number(9), Number(6), Number(2)], True),
        Function("", [Number(9), Number(7), Number(3)], True),
    ],
    "ex07.txt": [
        Function("", [Number(1), Number(3), Number(4)], True),
        Function("", [Number(1), Number(4), Number(5)], True),
        Function("", [Number(1), Number(5), Number(2)], True),
        Function("", [Number(1), Number(6), Number(9)], True),
        Function("", [Number(1), Number(7), Number(3)], True),
        Function("", [Number(2), Number(3), Number(8)], True),
        Function("", [Number(2), Number(4), Number(7)], True),
        Function("", [Number(2), Number(5), Number(3)], True),
        Function("", [Number(2), Number(6), Number(1)], True),
        Function("", [Number(2), Number(7), Number(9)], True),
        Function("", [Number(3), Number(3), Number(5)], True),
        Function("", [Number(3), Number(4), Number(8)], True),
        Function("", [Number(3), Number(5), Number(6)], True),
        Function("", [Number(3), Number(6), Number(4)], True),
        Function("", [Number(3), Number(7), Number(7)], True),
        Function("", [Number(4), Number(3), Number(3)], True),
        Function("", [Number(4), Number(4), Number(9)], True),
        Function("", [Number(4), Number(5), Number(7)], True),
        Function("", [Number(4), Number(6), Number(2)], True),
        Function("", [Number(4), Number(7), Number(6)], True),
        Function("", [Number(5), Number(1), Number(9)], True),
        Function("", [Number(5), Number(3), Number(6)], True),
        Function("", [Number(5), Number(4), Number(3)], True),
        Function("", [Number(5), Number(5), Number(4)], True),
        Function("", [Number(5), Number(6), Number(5)], True),
        Function("", [Number(5), Number(7), Number(1)], True),
        Function("", [Number(6), Number(1), Number(5)], True),
        Function("", [Number(6), Number(2), Number(4)], True),
        Function("", [Number(6), Number(3), Number(7)], True),
        Function("", [Number(6), Number(4), Number(1)], True),
        Function("", [Number(6), Number(5), Number(8)], True),
        Function("", [Number(6), Number(6), Number(6)], True),
        Function("", [Number(6), Number(7), Number(2)], True),
        Function("", [Number(7), Number(1), Number(4)], True),
        Function("", [Number(7), Number(2), Number(5)], True),
        Function("", [Number(7), Number(3), Number(2)], True),
        Function("", [Number(7), Number(4), Number(6)], True),
        Function("", [Number(7), Number(5), Number(1)], True),
        Function("", [Number(7), Number(6), Number(7)], True),
        Function("", [Number(8), Number(1), Number(8)], True),
        Function("", [Number(8), Number(2), Number(7)], True),
        Function("", [Number(8), Number(3), Number(1)], True),
        Function("", [Number(8), Number(4), Number(4)], True),
        Function("", [Number(8), Number(5), Number(9)], True),
        Function("", [Number(8), Number(6), Number(3)], True),
        Function("", [Number(9), Number(1), Number(6)], True),
        Function("", [Number(9), Number(2), Number(3)], True),
        Function("", [Number(9), Number(3), Number(9)], True),
        Function("", [Number(9), Number(4), Number(2)], True),
        Function("", [Number(9), Number(5), Number(5)], True),
        Function("", [Number(9), Number(6), Number(8)], True),
    ],
}
